apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-custom-css
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  custom.css: |
    header {
        background-color: black;
    }