apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.service.name}}-custom-css
  namespace: {{ .Values.release.namespace }}
  labels:
    app: {{ .Values.service.name}}
data:
  custom.css: |
    header {
        background-color: black;
    }