apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.service.name}}-filebrowser-config
  labels:
    app: {{ .Values.service.name}}
data:
  filebrowser.json: |
    {
      "branding": {
        "files": "/branding",
        "disableExternal": true
      }
    }