apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.service.name}}-filebrowser-config
  namespace: {{ .Values.release.namespace }}
  labels:
    app: {{ .Values.service.name}}
data:
  filebrowser.json: |
    {
      "branding": {
        "files": "/branding",
        "name": "SmartBrick"
      }
    }