{{- if .Values.persistence.enabled  }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.release.namespace }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- end }}